-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Drop existing tables to ensure clean slate
drop table if exists public.system_logs cascade;
drop table if exists public.reports cascade;
drop table if exists public.mutes cascade;
drop table if exists public.bans cascade;
drop table if exists public.chat_settings cascade;
drop table if exists public.messages cascade;
drop table if exists public.room_members cascade;
drop table if exists public.rooms cascade;
drop table if exists public.users cascade;

-- Users table (extends Supabase auth.users via triggers if needed, but for now we'll keep a separate public profile table or just use auth.users metadata. 
-- However, to match Laravel structure, let's create a public.users table that links to auth.users)
create table public.users (
  id bigint generated by default as identity primary key,
  supabase_user_id uuid references auth.users(id) on delete cascade,
  name text not null,
  email text not null unique,
  is_admin boolean default false,
  last_seen_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Rooms table
create table public.rooms (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  is_private boolean default false,
  created_by bigint references public.users(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Room Members table
create table public.room_members (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  room_id bigint references public.rooms(id) on delete cascade,
  role text default 'member', -- member, moderator, owner
  joined_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, room_id)
);

-- Events table
create table public.events (
  id bigint generated by default as identity primary key,
  name text not null,
  status text default 'scheduled', -- scheduled, active, completed, archived
  show_chat_history boolean default true,
  is_active boolean default false,
  start_time timestamp with time zone,
  end_time timestamp with time zone,
  window_title text default 'Arts and Entertainment',
  show_ads boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Messages table
create table public.messages (
  id bigint generated by default as identity primary key,
  room_id bigint references public.rooms(id) on delete cascade,
  user_id bigint references public.users(id) on delete cascade,
  event_id bigint references public.events(id) on delete set null, -- Link to event
  chat_mode text default 'Live Event', -- Snapshot of mode when sent
  history_is_visible boolean default true,
  content text not null,
  is_flagged boolean default false,
  flag_reason text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Chat Settings table
create table public.chat_settings (
  id bigint generated by default as identity primary key,
  is_chat_enabled boolean default true,
  is_scheduling_enabled boolean default false,
  window_start timestamp with time zone,
  window_end timestamp with time zone,
  maintenance_mode boolean default false,
  window_title text default 'Arts and Entertainment - Red Dragon Inn',
  max_message_length integer default 2000,
  max_messages_per_minute integer default 30,
  
  -- Event Modes
  event_mode text default 'Live Event', -- Pre-Show, Live Event, Afterparty, Quiet Mode
  
  -- Flow & Safety
  slow_mode_interval integer default 0,
  burst_protection_enabled boolean default false,
  max_burst_messages integer default 5,
  auto_mute_enabled boolean default false,
  auto_mute_violations integer default 3,
  allow_links boolean default false,
  allow_pixel_reactions boolean default true,
  profanity_filter_enabled boolean default true,
  
  -- Admin Signal Tools
  admin_highlight_enabled boolean default false,
  topic_prompt_text text,
  
  -- Automations
  crowd_surge_detection_enabled boolean default false,
  surge_threshold integer default 100,
  spam_burst_auto_mute boolean default false,
  inactivity_cleanup_enabled boolean default false,
  inactivity_cleanup_hours integer default 24,
  
  -- Aesthetic Controls
  window_border_style text default 'System95',
  color_theme text default 'Teal Base',
  scanline_intensity integer default 0,
  admin_badge_style text default 'Star Icon',
  
  -- Event Scheduling
  scheduled_system_messages_enabled boolean default false,
  system_message_content text,
  system_message_post_time timestamp with time zone,
  auto_mode_transition_enabled boolean default false,
  pre_show_time timestamp with time zone,
  live_event_time timestamp with time zone,
  afterparty_time timestamp with time zone,

  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Bans table
create table public.bans (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  room_id bigint references public.rooms(id) on delete cascade,
  reason text not null,
  expires_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Mutes table
create table public.mutes (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  room_id bigint references public.rooms(id) on delete cascade,
  reason text not null,
  expires_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Reports table
create table public.reports (
  id bigint generated by default as identity primary key,
  message_id bigint references public.messages(id) on delete cascade,
  reporter_id bigint references public.users(id) on delete cascade,
  reason text not null,
  status text default 'open', -- open, reviewing, resolved, dismissed
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- System Logs table
create table public.system_logs (
  id bigint generated by default as identity primary key,
  type text not null, -- auth, chat, moderation, system, error
  message text not null,
  meta jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- System Settings table
create table public.system_settings (
  id bigint generated by default as identity primary key,
  app_name text default 'ChronOps',
  tagline text,
  window_title_format text default '[App Name] – [Chatroom Title]',
  show_branding_footer boolean default true,
  
  -- Time, Locale & Formatting
  timezone text default 'UTC',
  time_format text default '24-hour', -- 12-hour, 24-hour
  date_format text default 'YYYY-MM-DD', -- MM/DD/YYYY, DD/MM/YYYY, YYYY-MM-DD
  show_seconds boolean default false,
  show_timestamps boolean default true,
  
  -- Data & Privacy
  message_retention_policy text default 'Forever', -- 24 hours, 7 days, 30 days, Forever
  allow_chat_log_export boolean default false,
  anonymize_exports boolean default true,
  log_ip_enabled boolean default true,
  
  -- Access & Admin Security
  admin_display_name text default 'Admin',
  require_password_for_dashboard boolean default true,
  auto_logout_enabled boolean default true,
  idle_timeout_minutes integer default 15,
  
  -- Notifications & Alerts
  notification_email text,
  alert_on_error boolean default true,
  alert_on_disconnect boolean default true,
  alert_on_surge boolean default false,
  sound_on_new_message boolean default false,
  sound_on_mention boolean default true,
  sound_on_warning boolean default true,
  
  -- Startup & Default Behavior
  default_event_mode text default 'Live Event',
  auto_open_chat boolean default true,
  auto_apply_snapshot boolean default false,
  show_closed_splash boolean default true,
  
  -- Integrations
  analytics_id text,
  webhook_url text,
  send_events_joined boolean default false,
  send_events_left boolean default false,
  send_events_message boolean default false,
  send_events_admin boolean default true,
  
  -- Advanced & Labs
  experimental_features boolean default false,
  show_dev_console boolean default false,

  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert default system settings
insert into public.system_settings (app_name) values ('ChronOps');

-- Create a trigger to automatically create a public user when a new auth user is created
drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user();

create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (supabase_user_id, name, email)
  values (new.id, new.raw_user_meta_data->>'name', new.email);
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
