-- Client Sessions: Tracks anonymous client IDs and their IPs
create table if not exists public.client_sessions (
  id uuid default gen_random_uuid() primary key,
  client_id text not null, -- Anonymous UUID generated by frontend
  ip_address text,
  user_agent text,
  created_at timestamptz default now(),
  last_seen_at timestamptz default now()
);

-- Index for fast lookups
create index if not exists idx_client_sessions_client_id on public.client_sessions(client_id);
create index if not exists idx_client_sessions_ip on public.client_sessions(ip_address);


-- Bans / Mutes
create table if not exists public.bans (
  id uuid default gen_random_uuid() primary key,
  client_id text, -- Can ban by ID
  ip_address text, -- Can ban by IP
  reason text,
  created_at timestamptz default now(),
  expires_at timestamptz, -- NULL = Permanent
  created_by uuid references auth.users(id), -- Admin who banned
  scope text check (scope in ('client', 'ip', 'both')) default 'client'
);

create index if not exists idx_bans_client_id on public.bans(client_id);
create index if not exists idx_bans_ip on public.bans(ip_address);

-- Enable RLS
alter table public.client_sessions enable row level security;
alter table public.bans enable row level security;

-- Policies
-- Only Service Role (Backend) can manage these tables fully.
-- Admins can READ/INSERT bans (via API).

create policy "Service Role Full Access Sessions"
  on public.client_sessions
  to service_role
  using (true)
  with check (true);

create policy "Service Role Full Access Bans"
  on public.bans
  to service_role
  using (true)
  with check (true);

-- Admin Access to Bans
create policy "Admins can view bans"
  on public.bans for select
  to authenticated
  using (
    exists (
      select 1 from public.users 
      where supabase_user_id = auth.uid() 
      and is_admin = true
    )
  );

create policy "Admins can insert bans"
  on public.bans for insert
  to authenticated
  with check (
    exists (
      select 1 from public.users 
      where supabase_user_id = auth.uid() 
      and is_admin = true
    )
  );

-- Admins can update/delete (to unban)
create policy "Admins can update bans"
  on public.bans for update
  to authenticated
  using (
    exists (
      select 1 from public.users 
      where supabase_user_id = auth.uid() 
      and is_admin = true
    )
  );

create policy "Admins can delete bans"
  on public.bans for delete
  to authenticated
  using (
    exists (
      select 1 from public.users 
      where supabase_user_id = auth.uid() 
      and is_admin = true
    )
  );
